[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remapping = [
    "@chainlink/contracts=lib/chainlink-brownie-contracts/contracts/",
    "@opnezeppelin/contracts=lib/openzeppelin-contract/contracts",
]
[invarient]
runs=128
depth=128
fail_on_revert=false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
